[package]
name = "provisioner-app"
version = "0.1.0"
authors = ["Conor Patrick <conor@solokeys.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apdu-dispatch = { git = "https://github.com/solokeys/apdu-dispatch", branch = "main" }
delog = "0.1.1"
heapless = "0.6"
heapless-bytes = "0.2.0"
lpc55-hal = { version = "0.2.1", features = ["littlefs", "rtic-peripherals"] }
littlefs2 = "0.2.2"
trussed = { git = "https://github.com/trussed-dev/trussed", branch = "main" }

[dependencies.nisty]
version = "0.1.0-alpha.5"
features = ["asn1-der", "cose"]

[dependencies.salty]
git = "https://github.com/ycrypto/salty"
branch = "main"
features = ["cose"]

[features]
log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []


