[package]
name = "provisioner-app"
version = "0.1.0"
authors = ["Conor Patrick <conor@solokeys.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apdu-dispatch = "0.1"
delog = "0.1"
heapless = "0.7"
heapless-bytes = "0.3"
lpc55-hal = { version = "0.3", features = ["littlefs", "rtic-peripherals"], optional = true }
nrf52840-pac = { version = "0.11", optional = true }
littlefs2 = "0.3.1"
salty = { version = "0.2", features = ["cose"] }
trussed = "0.1"

[dependencies.nisty]
version = "0.1.0-alpha.5"
features = ["asn1-der", "cose"]

[features]
log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

test-attestation = []

# supported boards / HALs
lpc55 = ["lpc55-hal"]
nrf52 = ["nrf52840-pac"]
