[package]
name = "fm11nc08"
version = "0.1.0"
authors = ["Conor Patrick <conor@solokeys.com>", "Nicolas Stalder <n@stalder.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cortex-m-funnel = "0.1.0-alpha.1"
bitflags = "1"
cortex-m = "0.6.1"
cortex-m-rt = "0.6.10"
embedded-hal = { version = "0.2.4", features = ["unproven"] }
nb = "1"
ufmt = "0.1.0"

logging = {path = "../logging"}

[features]
log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []
