[package]
name = "usbd-ccid"
version = "0.0.0-unreleased"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delog = "0.1.0"
embedded-time = "0.12"
heapless = "0.7"
# heapless-bytes = "0.3"
interchange = "0.2.0"
iso7816 = { git = "https://github.com/ycrypto/iso7816" }
usb-device = { version = "0.2.3", features = ["control-buffer-256"] }

[features]
default = []
highspeed-usb = []

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []
