[package]
name = "usbd-ccid"
version = "0.0.0-unreleased"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asn1derpy = "0.1.0"
heapless = "0.5.5"
heapless-bytes = { git = "https://github.com/ycrypto/heapless-bytes", branch = "main" }
interchange = { path = "../interchange" }


logging = { package = "logging", path = "../logging",version = "0.1.0" }

apdu-dispatch = { path = "../apdu-dispatch" }
iso7816 = { path = "../iso7816" }
untrusted = "0.7.1"
usb-device = { version = "0.2.3", features = ["control-buffer-256"] }

[features]
default = []
highspeed-usb = []

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []
