name: ci

on:
  pull_request:
  push:
    branches:
      - dev
      - main

env:
  CARGO_INCREMENTAL: 0
  # do not set RUSTFLAGES, would overrides .cargo/config (linker script, flip-link)

jobs:
  build-lpc55:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - board-lpcxpresso55
          - board-solo2
          # - board-okdoe1
        rust:
          - stable
    defaults:
      run:
        working-directory: runners/lpc55
    steps:
      - uses: actions/checkout@v1
      - name: Install littlefs2-sys/micro-ecc-sys build dependencies
        shell: bash
        run: |
          apt-get update && apt-get install sudo
          env && pwd && sudo apt-get update -y -qq && sudo apt-get install -y -qq llvm libc6-dev-i386 libclang-dev clang git
      - uses: fiam/arm-none-eabi-gcc@v1.0.4
        with:
          release: "9-2020-q2"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: thumbv8m.main-none-eabi
          override: true
          components: llvm-tools-preview
      # Use precompiled binutils
      - name: cargo install cargo-binutils
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: latest
          use-tool-cache: true
      - name: cargo install flip-link
        uses: actions-rs/install@v0.1
        with:
          crate: flip-link
          version: latest
          use-tool-cache: true
      - name: Build
        run: |
          cargo build --release --features ${{ matrix.board }}
      - name: Size
        run: |
          cargo size --release --features ${{ matrix.board }}
      - name: Upload Firmware
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: Firmware
          path: runners/lpc55/target/thumbv8m.main-none-eabi/release/runner
      - name: Build Provisioner
        run: |
          cargo build --release --features ${{ matrix.board }},provisioner-app,admin-app,trussed/clients-2,provisioner-app/test-attestation
      - name: Upload Provisioner
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: Provisioner
          path: runners/lpc55/target/thumbv8m.main-none-eabi/release/runner


  build-pc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # TODO: some build issue currently
          # - macos-latest
        rust:
          - stable
    defaults:
      run:
        working-directory: runners/pc
    steps:
      - uses: actions/checkout@v1
      - name: Install Linux build dependencies
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          apt-get update && apt-get install sudo
          sudo apt update -y -qq && sudo apt install -y -qq llvm libclang-dev build-essential clang

      # this is already installed
      # - name: Install macOS build dependencies
      #   if: matrix.os == 'macos-latest'
      #   shell: bash
      #   run: brew install llvm

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Build
        run: cargo build --release

